### ISSUE TITLE
Not Understand

### ISSUE THREAD

**Issue by manishkummar** [artyomd/Injector#11]
dependencies {
    inject 'com.airbnb.android:lottie:2.5.5'
    implementation 'com.android.support:appcompat-v7:27.1.1'
}
injectConfig {
    enabled = true
    groups = [
            "lottie": ["com.airbnb.android"]
    ]
}

Hi
I am trying to understand how to load the dex file in runtime, I got your example,your are loadinf airbnb dex at runtime from asset folder but i dont understand why u want to intialize again in gradle.

**Comment by artyomd** [comment]
To load a dex file first of all you must create that file. So to create that file from aar and jar dependencies you should use inject configuration. Inject configuration is similar to compileOnly configuration but when you run createInjectDexes task dex files are being created from all you inject dependencies

**Comment by manishkummar21** [comment]
Hi

I have android module and converted to aar file and also added in asset folder but i dont know what to add in the inject config,I think so its a package name?

**Comment by artyomd** [comment]
injectConfig groups field is only for grouping multiple dependencies in multiple dex files. If groups isn't specified it will create only one dex (injext.dex). Groups is just a map of dex names and list of artifact groups and artifact names
