### ISSUE TITLE
Could not find app.artyomd.injector:injector in mavenCenter

### ISSUE THREAD

**Issue by vasusachin** [artyomd/Injector#143]
Could not find app.artyomd.injector:injector
> Could not find app.artyomd.injector:injector:{0.5.0}.
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/app/artyomd/injector/injector/{0.5.0}/injector-{0.5.0}.pom
         https://dl.google.com/dl/android/maven2/app/artyomd/injector/injector/{0.5.0}/injector-{0.5.0}.jar
         https://repo.maven.apache.org/maven2/app/artyomd/injector/injector/{0.5.0}/injector-{0.5.0}.pom
         https://repo.maven.apache.org/maven2/app/artyomd/injector/injector/{0.5.0}/injector-{0.5.0}.jar
         https://jcenter.bintray.com/app/artyomd/injector/injector/{0.5.0}/injector-{0.5.0}.pom
         https://jcenter.bintray.com/app/artyomd/injector/injector/{0.5.0}/injector-{0.5.0}.jar

Added below lines in build.gradle
buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'app.artyomd.injector:injector:{0.5.0}'
    }
}

apply plugin: 'app.artyomd.injector'

**Comment by artyomdangizyan** [comment]
remove {}
`classpath 'app.artyomd.injector:injector:0.5.0'`
