### ISSUE TITLE
Failed to import plugin

### ISSUE THREAD

**Issue by ltym2016** [artyomd/Injector#229]
A problem occurred configuring root project 'ShellApp'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find app.artyomd.injector:injector:1.0.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/app/artyomd/injector/injector/1.0/injector-1.0.pom
       - https://dl.google.com/dl/android/maven2/app/artyomd/injector/injector/1.0/injector-1.0.pom
       - https://repo.maven.apache.org/maven2/app/artyomd/injector/injector/1.0/injector-1.0.pom
     Required by:
         project :

**Comment by artyomd** [comment]
There is no version `1.0`. The latest is `0.5`.
