### ISSUE TITLE
Allow for providing existing dex files as dependencies

### ISSUE THREAD

**Issue by jverne** [artyomd/Injector#230]
Sometimes we already have a dex file, and it would be nice to provide that to an Android library build to satsisy the dependency chain and to give the libaray what it needs at runtime. Tha tis, we don't have a dependency we want to change into a dexfile, but we already have a curated dexfile of our own.

Perhaps a variation on the "inject" dependency that uses a configuration where you can tell it how to find the dex or zipped dex files.

I can't think of a way that I can hack the classloader to load something from the assets for a library. But, more to the point, I'm not sure how I can use a dexfile to satisfy missing class dependencies in the library code. But the idea is to have a standalone library that can be consumed as a dependency by an app. But the app shouldn't know anything about the library assets.

I'm not sure if this project is still active or  not -- probably not -- so this is more or less me asking if anyone else has solved this problem, either by borrowing the ideas from this project or in another way.

**Comment by artyomd** [comment]
The inject-android library addresses the issue. It is described [in this section of the readme](https://github.com/artyomd/Injector#how-to-load-dex-files-at-runtime). t should be noted that there are two libraries included in this repository. If you are currently experiencing this issue or come across it in the future, the example app provides a useful reference, particularly the usage example found here: 
https://github.com/artyomd/Injector/blob/d9d1a17dd1632025fd9c1bcc3db7fb27dd60d8a6/injector-android-example/app/src/main/java/app/artyomd/injector/example/Application.java#L20
 I hope this helps.
