### ISSUE TITLE
Unable to get app.artyomd.injector:injector-android:0.3.6 from maven repo

### ISSUE THREAD

**Issue by jileshl** [artyomd/Injector#58]
I am unable to fetch "app.artyomd.injector:injector-android:0.3.6" from maven repository.

**Comment by artyomd** [comment]
injector-android is uploaded to maven central and everything works fine. You can find the artifact in the following URL: https://search.maven.org/artifact/app.artyomd.injector/injector-android/0.3.6/aar, if you are still unable to fetch it from the repository pls check your connection to maven central, or download aar and load it locally, or build it from sources. FYI I will try to attach build artifact to GitHub releases in the next releases
