### ISSUE TITLE
Doing injector from lib from repositories maven 

### ISSUE THREAD

**Issue by JFDionne** [artyomd/Injector#68]
Hi, it's a question and not a bug report.

Is there a way for use injector from lib coming from a repositories ? Since I don't have the source I can't add apply plugin: 'app.artyomd.injector' into those lib.

**Comment by artyomd** [comment]
Hi, pls make sure that your Gradle buildscript looks like this
```groovy
buildscript {
    repositories {
        google()
	mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:{latest-version}'
        classpath 'app.artyomd.injector:injector:{latest-version}'
    }
}
```
After this buildscript configuartion you must be able to use just apply plugin in your modules build.gradle file

**Comment by JFDionne** [comment]
Thank you very much !
