### ISSUE TITLE
Copying resources

### ISSUE THREAD

**Issue by sigaretaa** [artyomd/Injector#78]
First at all, thx for your useful lib. But..
I cloned your test project compiled and run it.  All works ok, but when i added just one  other lib `inject com.google.android.gms:play-services-ads:18.1.0`, `createInjectDebugDex` task said that  has some errors

command  javac -cp  is failed 
```
 Injector/injector-android-example/lib/build/exploded-aar/com.google.android.gms/play-services-ads-lite/18.1.0/R/com/google/android/gms/ads/R.java:5: error: cannot find symbol
    public static final int Theme_IAPTheme = app.artyomd.injector.example.lib.R.style.Theme_IAPTheme;
```

Unfortunately this is not the one library with a similar result.

**Comment by sigaretaa** [comment]
I've found error.
in Units class method unzip.
when you try create some file
`destinationFile.createNewFile();` the file could be in subfolder (..f1/f2/f3/file) but  f1,f2,f3 doesen't exist on that moment. so it easily fix with  `exists()` and `mkdirs()`

**Comment by artyomd** [comment]
@sigaretaa I was working on another project and didn't have time to update this project :( . So I have finally got some free time and I have done some improvements which will fix your problem. Pls check out version 0.5.0 and tell what you think :) btw thanks for opening the issue.

**Comment by artyomd** [comment]
This issue wasn't active for more than a month. I am closing this issue. @sigaretaa If you encounter a problem in version 0.5.0 pls open another issue
