### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [artyomd/Injector#8]
Greetings, Im a graphics designer here on Github and I would like to ask for your permission to design for your logo/icon that you maybe used for your future plans in your project. I want to help open source projects by designing logos or banners for there project. Thank you for your time reading this

Best regards
-jbeguna04

**Comment by artyomd** [comment]
Sure, it would be awesome.

**Comment by jbeguna04** [comment]
![injj](https://user-images.githubusercontent.com/35353768/42733063-e7bfd6e8-885d-11e8-84b6-9d1b86cd329a.png)

Here is the logo design for your project @artyomd , What do you think?
Feel free to open some suggestions. Thank You!

**Comment by artyomd** [comment]
@jbeguna04 those look awesome. Especially the black and dark blue ones

**Comment by jbeguna04** [comment]
@artyomd , Thank you for your response. The files are ready to be use. Do you want me to upload it here and make a pull request of it?

**Comment by artyomd** [comment]
Sure, go ahead.

**Comment by jbeguna04** [comment]
@artyomd , Already created created a pull request of the files and uploaded all the files there. Hope you can check it out. Thank you!

**Comment by artyomd** [comment]
@jbeguna04 Thanks for your work!
